### ISSUE TITLE
Cannot render AsyncAPI document with no components

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/java-spring-cloud-stream-template#120]
#### Describe the bug
https://github.com/asyncapi/java-spring-cloud-stream-template/blob/768f9cd0a77bff526bf7a7488e6f1ff85b141c46/hooks/post-process.js#L75 assumes there will always be components when that's not the case.

```json
{
  "asyncapi": "2.0.0",
  "info": {
    "title": "Streetlight",
    "version": "1.0.0"
  },
  "defaultContentType": "json",
  "channels": {
    "test": {
      "description": "Channel for the turn on command which should turn on the streetlight",
      "parameters": {
        "streetlight_id": {
          "description": "The ID of the streetlight",
          "schema": {
            "type": "string"
          }
        }
      },
      "publish": {
        "operationId": "test",
        "message": {
          "name": "TurnonCommand",
          "payload": {
            "x-parser-schema-id": "CustomClass",
            "$id": "CustomClass",
            "type": "object",
            "properties": {
              "prop1": { 
                  "type": "string"
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by damaru-inc** [comment]
I started working on this and I ran into problems.

First, I'd have to generate a POJO class for the payload. But what name should I use? It's quite valid to not have $id or title, just a map of properties. I could just make up a name in that case, or transform x-parser-schema-id which would be something like <anonymous-schema-1>, but then if another message was using the same construct, I'd end up with 2 identical classes with different names.

Next, instead of using $$schemas$$ I tried using $$objectSchema$$. The former was easy because it created names based on the schema name on objects/schemas, but the latter created files named http-example.com-root (taken from the $id of one of the schemas which was http://example.com/root.json) or anonymous-schema-3. So writing the logic to figure out what the Java class name should be, and then renaming the files, was non-trivial.

The way that the template currently works, it creates inner classes when the schema has nested schemas. I use the property name to generate the inner class name, which solves the problem of having anonymous inner schemas. But switching over to the new way means that I get a new file for every nested schema which complicates things.

Once I got these problems sorted out for one of my sample files, I ran a second sample file and got a whole new set of problems.

I'm not saying I won't fix this, but I'll have to take more time and figure out what's the best approach.

**Comment by jonaslagoni** [comment]
> Next, instead of using $$schemas$$ I tried using $$objectSchema$$. The former was easy because it created names based on the schema name on objects/schemas, but the latter created files named http-example.com-root (taken from the $id of one of the schemas which was http://example.com/root.json) or anonymous-schema-3.

Good point, it is definitely something we will have to look at, from a more general perspective for all skeleton code templates as well as for Modelina. Especially since we overuse `$id` to its purpose - https://json-schema.org/understanding-json-schema/structuring.html#id. Hopefully, this will be addressed by the outcome of https://github.com/json-schema-org/community/discussions/18.

>  So writing the logic to figure out what the Java class name should be, and then renaming the files, was non-trivial.

Definitely, especially since you are reaching the very edge case of Nunjucks which only generates the file as-is, so you would have to create some highly customized hooks 😟 A bit easier with the React renderer.

> The way that the template currently works, it creates inner classes when the schema has nested schemas. I use the property name to generate the inner class name, which solves the problem of having anonymous inner schemas. But switching over to the new way means that I get a new file for every nested schema which complicates things.

Yea I can completely relate, as you are definitely not the only one with this problem (I had it as well for [ts-nats-template to generate the schemas](https://github.com/asyncapi/ts-nats-template/blob/master/template/src/schemas/schema.ts.js) where I switched to Modelina because I simply did not want to deal with it on a template basis).

Not sure how to best help you out here as we are kinda in the middle of figuring out how to help you generate data models as accurately as possible as simple as possible. Not sure if you want to invest time into getting Modelina to a point where it can solve your problem here? 🤔 We can schedule a public call if you are interrested, just let me know.
